name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s /Applications/Xcode_12.5.app
      - run: cd platform/mac
      - run: make debug
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s /Applications/Xcode_12.5.app
      - run: cd platform/mac
      - run: make test
  release:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s /Applications/Xcode_12.5.app
      - run: cd platform/mac
      - run: make release
